#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # ImMemory
  spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
  spring.datasource.url=jdbc:hsqldb:mem:selection;DB_CLOSE_DELAY=-1
  spring.datasource.username=sa
  spring.datasource.password=
  spring.jpa.hibernate.ddl-auto=create

# Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  spring:
    jpa:
      #optional - show SQL statements in console.
      show-sql: true
      properties:
        javax:
          persistence:
            sharedCache:
              #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
              mode: ENABLE_SELECTIVE
        hibernate:
          #optional - enable SQL statements formatting.
          format_sql: true
          #optional - generate statistics to check if L2/query cache is actually being used.
          generate_statistics: true
          cache:
            #required - turn on L2 cache.
            use_second_level_cache: true
            #optional - turn on query cache.
            use_query_cache: true
            region:
              #required - classpath to cache region factory.
              factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

logging:
  level:
    root: WARN
    ru.javaops.topjava: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true